name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: 🚀 Features
    labels:
      - feature
  - title: 🐛 Bug Fixes
    labels:
      - bug
  - title: 🧰 Maintenance
    labels:
      - chore
  - title: ⚡ Improvements
    labels:
      - improvement

change-template: '- $TITLE (#$NUMBER)'

template: |
  ## 📦 Release Notes

  $CHANGES
