"""
Documentation Engine
=====================
Process-level singleton assembly and AI context export.

Import the singletons:
    from app.doc_engine import doc_index, doc_search, doc_indexer

AI context export:
    from app.doc_engine import AIContextExporter
    md = AIContextExporter.export(doc_indexer)
"""
from __future__ import annotations

import base64
import logging
from pathlib import Path
from typing import Optional

from app.doc_engine.completeness import CompletenessReport, DocCompletenessChecker, DoDCheck
from app.doc_engine.indexer import DocIndexer
from app.doc_engine.models import DocCategory, DocEntry, ServiceContract
from app.doc_engine.search import DocIndex, DocSearchEngine

logger = logging.getLogger("techforge.doc_engine")

# ── Process singletons ────────────────────────────────────────────────────────

doc_index   = DocIndex()
doc_search  = DocSearchEngine(doc_index)
doc_indexer = DocIndexer(doc_index)


# ── AI Context Exporter ───────────────────────────────────────────────────────

class AIContextExporter:
    """
    Generates a single consolidated Markdown document containing the entire
    platform knowledge base.

    Purpose: Provide Claude, ChatGPT, or Gemini with full platform context
             so they can assist developers without needing access to the
             source code.

    Usage:
        from app.doc_engine import AIContextExporter, doc_indexer
        markdown = AIContextExporter.export(doc_indexer)
    """

    SECTION_ORDER = [
        DocCategory.INTRO,
        DocCategory.ARCHITECTURE,
        DocCategory.GUIDE,
        DocCategory.SDK_BACKEND,
        DocCategory.SDK_FRONTEND,
        DocCategory.MANIFEST_REF,
        DocCategory.GOVERNANCE,
        DocCategory.SERVICE_MODULE,
        DocCategory.EXAMPLES,
        DocCategory.MARKETPLACE,
        DocCategory.FAQ,
        DocCategory.MODULE,
        DocCategory.MODULE_EXAMPLE,
    ]

    SECTION_TITLES = {
        DocCategory.INTRO:          "Introduction",
        DocCategory.ARCHITECTURE:   "Architecture",
        DocCategory.GUIDE:          "Developer Guide",
        DocCategory.SDK_BACKEND:    "SDK — Backend",
        DocCategory.SDK_FRONTEND:   "SDK — Frontend",
        DocCategory.MANIFEST_REF:   "Manifest Reference",
        DocCategory.GOVERNANCE:     "Documentation First Principle (§16)",
        DocCategory.SERVICE_MODULE: "Service Modules",
        DocCategory.EXAMPLES:       "Examples",
        DocCategory.MARKETPLACE:    "Marketplace",
        DocCategory.FAQ:            "FAQ",
        DocCategory.MODULE:         "Installed Module Documentation",
        DocCategory.MODULE_EXAMPLE: "Installed Module — Examples",
    }

    @classmethod
    def export(
        cls,
        indexer: DocIndexer,
        include_categories: Optional[list[DocCategory]] = None,
        publishers: Optional[dict] = None,
    ) -> str:
        """
        Generate the consolidated AI context Markdown document.

        Args:
            indexer:             The DocIndexer instance to read from.
            include_categories:  Subset of categories to include.
                                 Defaults to all.
            publishers:          {publisher_id: Publisher} pré-carregado pelo
                                 caller assíncrono (Fase 17 §7 — este método
                                 continua síncrono; sem isto, Trust Level nunca
                                 passa de UNVERIFIED, mesmo com publisher_id
                                 declarado no manifest).

        Returns:
            Single Markdown string ready to paste into an LLM context window.
        """
        categories = include_categories or cls.SECTION_ORDER
        lines: list[str] = []

        lines.append("# TechForge Platform — AI Context Document")
        lines.append("")
        lines.append(
            "> This document was auto-generated by TechForge Documentation Engine.\n"
            "> It provides complete platform context for AI-assisted module development.\n"
            "> Last regenerated from the live platform registry."
        )
        lines.append("")

        # ── Core documentation ────────────────────────────────────────────────
        for category in categories:
            if category in (DocCategory.MODULE, DocCategory.MODULE_EXAMPLE):
                continue   # modules handled separately below

            entries = doc_index.by_category(category)
            if not entries:
                continue

            lines.append("---")
            lines.append(f"## {cls.SECTION_TITLES[category]}")
            lines.append("")

            for entry in entries:
                lines.append(f"### {entry.title}")
                lines.append("")
                lines.append(entry.content)
                lines.append("")

        # ── Service contracts (Fase 8 — Service Registry) ──────────────────────
        contracts = indexer.all_contracts()
        if contracts:
            from app.service_registry.registry import service_registry

            lines.append("---")
            lines.append("## Service Contracts")
            lines.append("")
            for contract in contracts:
                lines.append(f"### {contract.service_id} ({contract.module_id})")
                lines.append("")
                lines.append(f"**Version:** {contract.version}")
                lines.append(f"**Description:** {contract.description}")
                lines.append("")
                descriptor = service_registry.find_service(contract.service_id)
                if descriptor:
                    lines.append(f"**Status:** {descriptor.status.value}")
                    lines.append("")
                if contract.capabilities:
                    lines.append(f"**Capabilities:** {', '.join(contract.capabilities)}")
                    lines.append("")
                if contract.dependencies:
                    lines.append(f"**Dependencies:** {', '.join(contract.dependencies)}")
                    lines.append("")
                for exp in contract.exports:
                    lines.append(f"#### `{exp.name}`")
                    lines.append(f"{exp.description}")
                    if exp.parameters:
                        lines.append("")
                        lines.append("**Parameters:**")
                        for p in exp.parameters:
                            req = "" if p.get("required", True) else " *(optional)*"
                            lines.append(f"- `{p['name']}` ({p['type']}){req}: {p['description']}")
                    if exp.returns:
                        lines.append(f"\n**Returns:** {exp.returns}")
                    if exp.examples:
                        lines.append("\n**Examples:**")
                        lines.append("```")
                        for ex in exp.examples:
                            lines.append(ex)
                        lines.append("```")
                    lines.append("")

        # ── Dependency Governance (Fase 8.1) ───────────────────────────────────
        from app.dependency_engine.graph import DependencyGraph
        from app.module_engine.registry import registry as module_registry
        from app.service_registry.registry import service_registry

        graph = DependencyGraph.build(module_registry, service_registry)
        if graph.edges:
            lines.append("---")
            lines.append("## Dependency Governance")
            lines.append("")
            lines.append("```mermaid")
            lines.append(graph.export_mermaid())
            lines.append("```")
            lines.append("")

        # ── Module Runtime Context (Fase 9 §28) ────────────────────────────────
        from app.module_runtime.state import module_runtime_registry

        runtime_entries = module_runtime_registry.list_all()
        if runtime_entries:
            lines.append("---")
            lines.append("## Module Runtime Context")
            lines.append("")
            for e in sorted(runtime_entries, key=lambda e: e.module_id):
                lines.append(f"### {e.module_id}")
                lines.append(f"**Runtime State:** {e.state.value}")
                if e.last_error:
                    lines.append(f"**Last error:** {e.last_error}")
                if e.last_execution:
                    lines.append(f"**Last execution:** {e.last_execution.isoformat()}")
                lines.append("")

        # ── Module Trust (Fase 10 §27) ──────────────────────────────────────────
        from app.core.settings import settings
        from app.module_engine.enums import ModuleStatus as _MS
        from app.module_trust.integrity import verify_integrity
        from app.module_trust.signature import canonical_manifest_bytes, default_signature_provider
        from app.module_trust.trust import TrustResolver

        installed_entries = [e for e in module_registry.all() if e.status == _MS.INSTALLED]
        if installed_entries:
            lines.append("---")
            lines.append("## Module Trust")
            lines.append("")
            for e in sorted(installed_entries, key=lambda e: e.module_id):
                package_dir = settings.MODULES_INSTALLED_PATH / e.module_id
                integrity_result = verify_integrity(package_dir)
                raw = e.manifest_raw or {}
                publisher_field = raw.get("publisher")
                publisher_id = (publisher_field.get("id")
                               if isinstance(publisher_field, dict) else publisher_field)
                publisher = publishers.get(publisher_id) if publishers and publisher_id else None
                signature_value = raw.get("signature")
                signature_bytes = base64.b64decode(signature_value) if signature_value else None
                signature_status = default_signature_provider.verify(
                    data=canonical_manifest_bytes(raw), signature=signature_bytes,
                    public_key=publisher.public_key if publisher else None,
                ).value
                trust_level = TrustResolver.resolve(integrity_result.status, publisher, signature_status)

                lines.append(f"### {e.module_id}")
                lines.append(f"**Trust Level:** {trust_level.value}")
                lines.append(f"**Integrity:** {integrity_result.status.value}")
                if publisher_id:
                    lines.append(f"**Publisher:** {publisher_id}")
                lines.append("")

        # ── Module Catalog (Fase 11 §25) ─────────────────────────────────────────
        # Provide context about available catalog sources and remote installation
        try:
            from app.db.database import AsyncSessionLocal
            from app.package_manager.catalog_aggregator import CatalogAggregator
            from app.services.catalog_source import CatalogSourceService

            # Note: This section builds without actual DB query
            # (AI context is generated server-side on demand, not in background)
            lines.append("---")
            lines.append("## Module Catalog")
            lines.append("")
            lines.append("### Configured Sources")
            lines.append("")
            lines.append("Catalog sources are configured in the platform and define where modules can be discovered:")
            lines.append("")
            lines.append("1. **Local Repository** (`modules/repository/`) — Always available")
            lines.append("   - Modules in `.mod` format (ZIP archives)")
            lines.append("   - Fast discovery; no network required")
            lines.append("")
            lines.append("2. **Official Catalog** (TechForge-maintained)")
            lines.append("   - URL: Configured in settings")
            lines.append("   - Metada: `index.json` (one fetch per poll period)")
            lines.append("   - Installation: Downloads `.mod` from official repository")
            lines.append("")
            lines.append("3. **Custom Catalogs** (User-configured)")
            lines.append("   - Multiple sources allowed")
            lines.append("   - URL: Provided by user (GitHub repo, self-hosted, etc.)")
            lines.append("   - Discovery: Via GitHub Contents API + folder convention (`modules/<id>/manifest.yaml`)")
            lines.append("   - Installation: On-demand; platform fetches files and zips them")
            lines.append("")
            lines.append("### Installation Flow")
            lines.append("")
            lines.append("Remote module installation is **asynchronous** with progress tracking:")
            lines.append("")
            lines.append("1. **Acquisition Phase** — Resolves source and fetches module files to local cache")
            lines.append("2. **Validation Phase** — Verifies manifest, integrity, compatibility")
            lines.append("3. **Installation Phase** — Runs standard package manager install pipeline")
            lines.append("4. **Terminal State** — DONE (success) or FAILED (with error message)")
            lines.append("")
            lines.append("Users poll `GET /marketplace/install-jobs/{job_id}` for progress. No background retry.")
            lines.append("")
            lines.append("### Cache & TTL")
            lines.append("")
            lines.append("Module discovery results are cached per source with a configurable TTL (default: 15 minutes).")
            lines.append("Manual refresh forces immediate fetch, bypassing cache.")
            lines.append("")
        except Exception as e:
            logger.warning(f"Failed to build Module Catalog section for AI context: {e}")

        # ── Module documentation (overview + examples grouped per module) ─────
        wants_modules  = DocCategory.MODULE in categories
        wants_examples = DocCategory.MODULE_EXAMPLE in categories
        if wants_modules or wants_examples:
            module_entries = []
            if wants_modules:
                module_entries += doc_index.by_category(DocCategory.MODULE)
            if wants_examples:
                module_entries += doc_index.by_category(DocCategory.MODULE_EXAMPLE)

            if module_entries:
                lines.append("---")
                lines.append("## Installed Module Documentation")
                lines.append("")
                # Group by module_id; within each module, overview docs first
                by_module: dict[str, list[DocEntry]] = {}
                for e in module_entries:
                    by_module.setdefault(e.module_id or "unknown", []).append(e)
                for mod_id, entries in sorted(by_module.items()):
                    entries.sort(key=lambda e: (e.category != DocCategory.MODULE, e.order, e.title))
                    lines.append(f"### Module: {mod_id}")
                    lines.append("")
                    for entry in entries:
                        tag = " (example)" if entry.category == DocCategory.MODULE_EXAMPLE else ""
                        lines.append(f"#### {entry.title}{tag}")
                        lines.append(entry.content)
                        lines.append("")

        return "\n".join(lines)
