"""
Documentation Engine
=====================
Process-level singleton assembly and AI context export.

Import the singletons:
    from app.doc_engine import doc_index, doc_search, doc_indexer

AI context export:
    from app.doc_engine import AIContextExporter
    md = AIContextExporter.export(doc_indexer)
"""
from __future__ import annotations

import logging
from pathlib import Path
from typing import Optional

from app.doc_engine.models import DocCategory, DocEntry, ServiceContract
from app.doc_engine.search import DocIndex, DocSearchEngine
from app.doc_engine.indexer import DocIndexer
from app.doc_engine.completeness import DocCompletenessChecker, CompletenessReport, DoDCheck

logger = logging.getLogger("techforge.doc_engine")

# ── Process singletons ────────────────────────────────────────────────────────

doc_index   = DocIndex()
doc_search  = DocSearchEngine(doc_index)
doc_indexer = DocIndexer(doc_index)


# ── AI Context Exporter ───────────────────────────────────────────────────────

class AIContextExporter:
    """
    Generates a single consolidated Markdown document containing the entire
    platform knowledge base.

    Purpose: Provide Claude, ChatGPT, or Gemini with full platform context
             so they can assist developers without needing access to the
             source code.

    Usage:
        from app.doc_engine import AIContextExporter, doc_indexer
        markdown = AIContextExporter.export(doc_indexer)
    """

    SECTION_ORDER = [
        DocCategory.INTRO,
        DocCategory.ARCHITECTURE,
        DocCategory.GUIDE,
        DocCategory.SDK_BACKEND,
        DocCategory.SDK_FRONTEND,
        DocCategory.MANIFEST_REF,
        DocCategory.GOVERNANCE,
        DocCategory.SERVICE_MODULE,
        DocCategory.EXAMPLES,
        DocCategory.MARKETPLACE,
        DocCategory.FAQ,
        DocCategory.MODULE,
        DocCategory.MODULE_EXAMPLE,
    ]

    SECTION_TITLES = {
        DocCategory.INTRO:          "Introduction",
        DocCategory.ARCHITECTURE:   "Architecture",
        DocCategory.GUIDE:          "Developer Guide",
        DocCategory.SDK_BACKEND:    "SDK — Backend",
        DocCategory.SDK_FRONTEND:   "SDK — Frontend",
        DocCategory.MANIFEST_REF:   "Manifest Reference",
        DocCategory.GOVERNANCE:     "Documentation First Principle (§16)",
        DocCategory.SERVICE_MODULE: "Service Modules",
        DocCategory.EXAMPLES:       "Examples",
        DocCategory.MARKETPLACE:    "Marketplace",
        DocCategory.FAQ:            "FAQ",
        DocCategory.MODULE:         "Installed Module Documentation",
        DocCategory.MODULE_EXAMPLE: "Installed Module — Examples",
    }

    @classmethod
    def export(
        cls,
        indexer: DocIndexer,
        include_categories: Optional[list[DocCategory]] = None,
    ) -> str:
        """
        Generate the consolidated AI context Markdown document.

        Args:
            indexer:             The DocIndexer instance to read from.
            include_categories:  Subset of categories to include.
                                 Defaults to all.

        Returns:
            Single Markdown string ready to paste into an LLM context window.
        """
        categories = include_categories or cls.SECTION_ORDER
        lines: list[str] = []

        lines.append("# TechForge Platform — AI Context Document")
        lines.append("")
        lines.append(
            "> This document was auto-generated by TechForge Documentation Engine.\n"
            "> It provides complete platform context for AI-assisted module development.\n"
            "> Last regenerated from the live platform registry."
        )
        lines.append("")

        # ── Core documentation ────────────────────────────────────────────────
        for category in categories:
            if category in (DocCategory.MODULE, DocCategory.MODULE_EXAMPLE):
                continue   # modules handled separately below

            entries = doc_index.by_category(category)
            if not entries:
                continue

            lines.append(f"---")
            lines.append(f"## {cls.SECTION_TITLES[category]}")
            lines.append("")

            for entry in entries:
                lines.append(f"### {entry.title}")
                lines.append("")
                lines.append(entry.content)
                lines.append("")

        # ── Service contracts ─────────────────────────────────────────────────
        contracts = indexer.all_contracts()
        if contracts:
            lines.append("---")
            lines.append("## Service Contracts")
            lines.append("")
            for contract in contracts:
                lines.append(f"### {contract.service_id} ({contract.module_id})")
                lines.append("")
                lines.append(f"**Version:** {contract.version}")
                lines.append(f"**Description:** {contract.description}")
                lines.append("")
                if contract.dependencies:
                    lines.append(f"**Dependencies:** {', '.join(contract.dependencies)}")
                    lines.append("")
                for exp in contract.exports:
                    lines.append(f"#### `{exp.name}`")
                    lines.append(f"{exp.description}")
                    if exp.parameters:
                        lines.append("")
                        lines.append("**Parameters:**")
                        for p in exp.parameters:
                            req = "" if p.get("required", True) else " *(optional)*"
                            lines.append(f"- `{p['name']}` ({p['type']}){req}: {p['description']}")
                    if exp.returns:
                        lines.append(f"\n**Returns:** {exp.returns}")
                    if exp.examples:
                        lines.append("\n**Examples:**")
                        lines.append("```")
                        for ex in exp.examples:
                            lines.append(ex)
                        lines.append("```")
                    lines.append("")

        # ── Module documentation (overview + examples grouped per module) ─────
        wants_modules  = DocCategory.MODULE in categories
        wants_examples = DocCategory.MODULE_EXAMPLE in categories
        if wants_modules or wants_examples:
            module_entries = []
            if wants_modules:
                module_entries += doc_index.by_category(DocCategory.MODULE)
            if wants_examples:
                module_entries += doc_index.by_category(DocCategory.MODULE_EXAMPLE)

            if module_entries:
                lines.append("---")
                lines.append("## Installed Module Documentation")
                lines.append("")
                # Group by module_id; within each module, overview docs first
                by_module: dict[str, list[DocEntry]] = {}
                for e in module_entries:
                    by_module.setdefault(e.module_id or "unknown", []).append(e)
                for mod_id, entries in sorted(by_module.items()):
                    entries.sort(key=lambda e: (e.category != DocCategory.MODULE, e.order, e.title))
                    lines.append(f"### Module: {mod_id}")
                    lines.append("")
                    for entry in entries:
                        tag = " (example)" if entry.category == DocCategory.MODULE_EXAMPLE else ""
                        lines.append(f"#### {entry.title}{tag}")
                        lines.append(entry.content)
                        lines.append("")

        return "\n".join(lines)
